#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: eurekaserver-deployment
#  labels:
#    app: eurekaserver
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: eurekaserver
#  template:
#    metadata:
#      labels:
#        app: eurekaserver
#    spec:
#      containers:
#        - name: eurekaserver
#          imagePullPolicy: Never
#          image: eurekaserver
#          ports:
#            - containerPort: 8761
#
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: eurekaserver-service
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 8761
#      targetPort: 8761
#  selector:
#    app: eurekaserver